### PR TITLE
Fixed build constants error and updated build.gradle

### LINKED ISSUE #5: Copy over .gitignore and Remove BuildConstants
Since the .gitignore file wasn't up to date, BuildConstants was accidentally added to your repo. Just copy the gitignore from a previous repository and delete that file.

### PR DESCRIPTION
**Pull request by codeall1234**
Resolves #5

### CODE REVIEW

**Review by anees2869 — APPROVED** [review]

**Review by VMFortress — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/subsystems/indexer/IndexerIOTalonFX.java [hunk 1]
```diff
@@ -30,6 +30,7 @@ public class IndexerIOTalonFX extends IndexerIO {
   private final StatusSignal<Current> indexerCurrent;
   private final StatusSignal<Temperature> indexerTemperature;
   private final StatusSignal<Integer> indexerVersion;
+
```
Comment (Advay17) [inline src/main/java/frc/robot/subsystems/indexer/IndexerIOTalonFX.java]: Nit: remove

**Review by Advay17 — APPROVED** [review]
@codeall1234 I'll approve this for now since we really need to get PRs rolling, but please try to avoid adding whitespace changes to files that don't have changed content, it doesn't look like a Spotless addition either.

**Review by VMFortress — APPROVED** [review]
Same as Kavin said. Best to remove those but I'll approve as its otherwise good.

**Review by anees2869 — APPROVED** [review]
